-- PROJECTION

SELECT ENAME FROM EMP;

SELECT SAL FROM EMP;

SELECT ENAME,SAL FROM EMP;

SELECT JOB FROM EMP;

SELECT EMPNO FROM EMP;

SELECT HIREDATE, COMM FROM EMP;

SELECT DEPTNO, LOC FROM DEPT;

-- DISTINCT

SELECT DISTINCT SAL FROM EMP;

SELECT DISTINCT SAL, ENAME FROM EMP;

-- EXPRESSION

SELECT SAL*12 FROM EMP;

SELECT SAL*6 FROM EMP;

SELECT SAL*12+ SAL*12*10/100 FROM EMP;

SELECT SAL*6 - SAL*6*15/100 FROM EMP;

SELECT SAL + SAL*20/100 FROM EMP;

SELECT SAL*12 +1000 FROM EMP;

SELECT SAL-50 FROM EMP;

SELECT EMP.* , SAL*12 FROM EMP;

-- SELECTION 

SELECT ENAME FROM EMP WHERE DEPTNO = 20;

SELECT * FROM EMP WHERE SAL>1000;

SELECT * FROM EMP WHERE ENAME='SMITH';

SELECT * FROM EMP WHERE HIREDATE = '17-DEC-80';

SELECT * FROM EMP WHERE HIREDATE <'01-JAN-81';

SELECT SAL*12 ANNUAL_SAL FROM EMP WHERE ENAME='SMITH';

SELECT ENAME FROM EMP WHERE JOB='CLERK';

SELECT SAL FROM EMP WHERE JOB='SALESMAN';

SELECT * FROM EMP WHERE SAL>2000;

SELECT * FROM EMP WHERE ENAME='JAMES';

SELECT * FROM EMP WHERE HIREDATE > '01-JAN-81';

SELECT ENAME,SAL, SAL*12 FROM EMP WHERE SAL*12>12000;

SELECT EMPNO FROM EMP WHERE DEPTNO=30;

SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE<'01-JAN-81';

SELECT * FROM EMP WHERE JOB='MANAGER';

SELECT ENAME,SAL FROM EMP WHERE COMM=1400;

SELECT * FROM EMP WHERE COMM>SAL;

SELECT EMPNO FROM EMP WHERE HIREDATE < '01-JAN-87';

SELECT * FROM EMP WHERE JOB='ANALYST';

SELECT * FROM EMP WHERE SAL>2000;

-- LOGICAL OPERATOR

SELECT ENAME FROM EMP WHERE DEPTNO=20 AND SAL>1000;

SELECT * FROM EMP WHERE DEPTNO=10 OR DEPTNO=20;

SELECT * FROM EMP WHERE JOB!='CLERK';

SELECT * FROM EMP WHERE( DEPTNO=10 OR DEPTNO=20 ) AND JOB='CLERK';

SELECT * FROM EMP WHERE JOB='CLERK' AND SAL<1500;

SELECT ENAME , HIREDATE FROM EMP WHERE JOB='MANAGER' AND DEPTNO=30;

SELECT EMP.*,SAL*12 AS "ANNUAL SALARY" FROM EMP WHERE DEPTNO=30 AND JOB='SALESMAN' AND SAL*12 >1400;

SELECT * FROM EMP WHERE DEPTNO= 30 OR JOB='ANALYST';

SELECT ENAME FROM EMP WHERE SAL<1100 AND JOB='CLERK'; 

SELECT ENAME,JOB,DEPTNO FROM EMP WHERE JOB='CLERK' AND(DEPTNO=10 OR DEPTNO=20);

SELECT * FROM EMP WHERE (JOB='CLERK' OR JOB='MANAGER') AND DEPTNO=10;

SELECT ENAME FROM EMP WHERE DEPTNO=10 OR DEPTNO=20 OR DEPTNO=30 OR DEPTNO=40;

SELECT * FROM EMP WHERE EMPNO=7902 OR EMPNO=7839;

SELECT * FROM EMP WHERE JOB='MANAGER' OR JOB='CLERK' OR JOB='SALESMAN';

SELECT ENAME FROM EMP WHERE HIREDATE>'31-DEC-81'AND HIREDATE <'01-JAN-87';

SELECT * FROM EMP WHERE SAL>1250 AND SAL<3000;

SELECT ENAME FROM EMP WHERE HIREDATE> '31-DEC-81' AND (DEPTNO=10 OR DEPTNO=30);

SELECT ENAME ,SAL*12 FROM EMP WHERE (JOB='MANAGER' OR JOB='CLERK')AND(DEPTNO=10 OR DEPTNO=20);

SELECT EMP.* , SAL*12 AS ANNUAL_SAL FROM EMP WHERE SAL>1000 AND SAL<4000 AND SAL*12 >1500;

SELECT * FROM EMP WHERE DEPTNO!= 10 AND DEPTNO!= 20;

SELECT EMP.*, SAL*12 FROM EMP WHERE JOB!='ANALYST' AND JOB!='MANAGER';

-- SPECIAL OPERATOR 

SELECT * FROM EMP WHERE DEPTNO IN (10,20,30);

SELECT * FROM EMP WHERE JOB IN ('CLERK','ANALYST');

SELECT * FROM EMP WHERE DEPTNO NOT IN (10,20);

SELECT * FROM EMP WHERE SAL BETWEEN 1000 AND 4000;

SELECT * FROM EMP WHERE SAL BETWEEN 1000 AND 3000;

SELECT * FROM EMP WHERE COMM BETWEEN 1000 AND 2000;

SELECT * FROM EMP WHERE HIREDATE BETWEEN '01-JAN-1981' AND '31-DEC-81';

SELECT * FROM EMP WHERE SAL NOT BETWEEN 1000 AND 3000;

SELECT * FROM EMP WHERE ENAME LIKE 'A%';

SELECT ENAME FROM EMP WHERE ENAME LIKE '%S';

SELECT ENAME FROM EMP WHERE ENAME LIKE '%A%';

SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%S';

SELECT * FROM EMP WHERE HIREDATE LIKE '%81';

SELECT * FROM EMP WHERE HIREDATE LIKE '%JAN%';

SELECT ENAME FROM EMP WHERE ENAME LIKE '%A%A%';

SELECT ENAME FROM EMP WHERE ENAME LIKE '%LL%';

SELECT * FROM EMP WHERE SAL LIKE '%50';

SELECT * FROM EMP WHERE ENAME LIKE '_A%';

SELECT ENAME FROM EMP WHERE ENAME LIKE '%E_';

SELECT * FROM EMP WHERE SAL LIKE '____';

SELECT ENAME FROM EMP WHERE ENAME NOT LIKE 'A%';

SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%' OR ENAME LIKE'E%'OR ENAME LIKE'I%'OR ENAME LIKE'O%'OR ENAME LIKE'U%';

SELECT ENAME FROM EMP WHERE ENAME NOT LIKE 'A%' AND ENAME NOT LIKE'E%' AND ENAME NOT LIKE'I%' AND ENAME NOT  LIKE'O%' AND ENAME NOT LIKE'U%';

SELECT * FROM EMP WHERE COMM IS NULL;

SELECT * FROM EMP WHERE COMM IS NOT NULL;

SELECT * FROM EMP WHERE DEPTNO IN (10,20);

SELECT ENAME FROM EMP WHERE HIREDATE LIKE '%82';

SELECT ENAME , SAL FROM EMP WHERE COMM IS NOT NULL;

SELECT * FROM EMP WHERE JOB='CLERK' AND DEPTNO IN(10,20) AND ENAME LIKE '%A%';

SELECT ENAME , HIREDATE FROM EMP WHERE HIREDATE BETWEEN '31-DEC-82' AND '01-JAN-87';

SELECT * FROM EMP WHERE JOB='ANALYST' AND SAL LIKE '____';

SELECT * FROM EMP WHERE JOB='SALESMAN' AND COMM IS NULL;

SELECT ENAME,SAL FROM EMP WHERE HIREDATE LIKE '%99' AND DEPTNO IN(10,40); 

SELECT * FROM EMP WHERE ENAME LIKE '%L%L%' AND JOB= 'MANAGER';

SELECT ENAME FROM EMP WHERE COMM IS NOT NULL AND SAL IS NULL;

SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%' OR ENAME LIKE 'J%' OR ENAME LIKE 'S%';

SELECT ENAME FROM EMP WHERE ENAME NOT LIKE '__A%';

SELECT * FROM EMP WHERE JOB='MANAGER' AND HIREDATE>'31-DEC-84' AND ENAME LIKE '%S';

-- MULTI-ROW FUNCTION

SELECT MAX(SAL) FROM EMP WHERE JOB='CLERK';

SELECT SUM(SAL) FROM EMP;

SELECT COUNT(*) FROM EMP WHERE ENAME LIKE '%A%';

SELECT MAX(SAL), MIN(SAL) FROM EMP;

SELECT COUNT(*) FROM EMP WHERE SAL>2000 AND DEPTNO=10;

SELECT SUM(SAL) FROM EMP WHERE JOB='CLERK';

SELECT AVG(SAL) FROM EMP;

SELECT COUNT(*) FROM EMP WHERE ENAME LIKE 'A%';

SELECT COUNT(*) FROM EMP WHERE JOB IN('CLERK','MANAGER');

SELECT SUM(SAL) FROM EMP WHERE HIREDATE LIKE '%FEB%';

-- GROUP BY

SELECT COUNT(*),DEPTNO 
FROM EMP 
GROUP BY DEPTNO;

SELECT MAX(SAL),DEPTNO FROM EMP WHERE JOB='CLERK' GROUP BY DEPTNO;

SELECT COUNT(*),DEPTNO FROM EMP WHERE ENAME LIKE '%A%' GROUP BY DEPTNO;

SELECT COUNT(*),DEPTNO FROM EMP WHERE JOB!='PRESIDENT' GROUP BY DEPTNO;

SELECT SUM(SAL),JOB FROM EMP GROUP BY JOB;

SELECT COUNT(*) FROM EMP WHERE JOB='MANAGER' GROUP BY DEPTNO;

SELECT AVG(SAL),DEPTNO FROM EMP WHERE DEPTNO != 20 GROUP BY DEPTNO;

SELECT COUNT(*),JOB FROM EMP WHERE ENAME LIKE '%A%' GROUP BY JOB;

SELECT COUNT(*),AVG(SAL),DEPTNO FROM EMP WHERE SAL>2000 GROUP BY DEPTNO;

SELECT COUNT(*),MAX(SAL),JOB FROM EMP GROUP BY JOB;

SELECT SUM(SAL) , COUNT(JOB),DEPTNO FROM EMP WHERE JOB ='SALESMAN' GROUP BY DEPTNO;

SELECT MAX(SAL),DEPTNO FROM EMP GROUP BY DEPTNO;

SELECT COUNT(SAL),SAL FROM EMP GROUP BY SAL;

-- HAVING

SELECT COUNT(*),DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(DEPTNO)>4;

SELECT MIN(SAL),MAX(SAL) FROM EMP GROUP BY DEPTNO HAVING MIN(SAL)>1000;

SELECT COUNT(*),DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(*) BETWEEN 2 AND 5;

SELECT COUNT(*),HIREDATE,DEPTNO FROM EMP GROUP BY HIREDATE, DEPTNO HAVING COUNT(*)>1;

SELECT COUNT(*),HIREDATE ,DEPTNO FROM EMP GROUP BY HIREDATE ,DEPTNO HAVING COUNT(*)>2;

SELECT COUNT(*) FROM EMP GROUP BY SAL, DEPTNO HAVING COUNT(*)>2;

SELECT COUNT(*) FROM EMP GROUP BY ENAME , DEPTNO HAVING COUNT(*)>2;

SELECT COUNT(*) FROM EMP GROUP BY ENAME , DEPTNO,SAL HAVING COUNT(*)>2;

SELECT COUNT(*) FROM EMP GROUP BY SAL, DEPTNO,HIREDATE HAVING COUNT(*)>2;

SELECT DEPTNO, COUNT(*) FROM EMP WHERE JOB='CLERK' GROUP BY DEPTNO HAVING COUNT(*)>1;

SELECT DEPTNO, SUM(SAL) FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>4;

SELECT COUNT(*),JOB,SUM(SAL) FROM EMP WHERE SAL>1200 GROUP BY JOB HAVING SUM(SAL)>3800;  

SELECT DEPTNO , COUNT(*) FROM EMP WHERE JOB='MANAGER' GROUP BY DEPTNO HAVING COUNT(*)>1;

SELECT JOB,MAX(SAL) FROM EMP GROUP BY JOB HAVING MAX(SAL)>2800;

SELECT SAL , COUNT(*) FROM EMP GROUP BY SAL HAVING COUNT(SAL)>1;

SELECT HIREDATE , COUNT(*) FROM EMP GROUP BY HIREDATE HAVING COUNT(*)>1;

SELECT AVG(SAL),DEPTNO FROM EMP GROUP BY DEPTNO HAVING AVG(SAL)<3000;

SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%A%' AND ENAME LIKE '%S%' GROUP BY DEPTNO HAVING COUNT(*)>=3;

SELECT MIN(SAL), MAX(SAL),JOB FROM EMP GROUP BY JOB HAVING MIN(SAL)>1000 AND MAX(SAL)<5000;

-- ORDER BY

SELECT SAL FROM EMP ORDER BY SAL ASC;

SELECT ENAME FROM EMP ORDER BY ENAME;

SELECT SAL FROM EMP ORDER BY SAL DESC;

-- SUBQUERY

-- CASE1

SELECT ENAME FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='MILLER' );

SELECT * FROM EMP WHERE JOB= (SELECT JOB FROM EMP WHERE ENAME ='ALLEN');

SELECT * FROM EMP WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='MILLER');

SELECT * FROM EMP WHERE SAL>1000 AND DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='JAMES');

SELECT * FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='SMITH') AND SAL<(SELECT SAL FROM EMP WHERE ENAME='KING');

SELECT ENAME FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME='ADAMS');

SELECT ENAME ,SAL FROM EMP WHERE SAL<(SELECT SAL FROM EMP WHERE ENAME='KING');

SELECT ENAME,DEPTNO FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='JONES');

SELECT ENAME,JOB FROM EMP WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='JAMES');

SELECT EMPNO,ENAME,SAL*12 AS "ANNUAL SAL" FROM EMP WHERE SAL*12>(SELECT SAL*12 FROM EMP WHERE ENAME= 'WARD');

SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE<(SELECT HIREDATE FROM EMP WHERE ENAME='SCOTT');

SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE JOB='PRESIDENT');

SELECT ENAME,SAL FROM EMP WHERE SAL<(SELECT SAL FROM EMP WHERE EMPNO=7839);

SELECT * FROM EMP WHERE HIREDATE<(SELECT HIREDATE FROM EMP WHERE ENAME='MILLER');

SELECT ENAME, EMPNO FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='ALLEN');

-- CASE2

SELECT DNAME FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SMITH');

SELECT LOC FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='MILLER');

SELECT * FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING');

SELECT * FROM EMP WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='SMITH') AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');

SELECT DNAME FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SMITH');

SELECT DNAME,LOC FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='KING' );

SELECT LOC FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE EMPNO=7902);

SELECT DNAME, LOC,DEPTNO FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%R');

SELECT DNAME FROM DEPT wHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE JOB='PRESIDENT');

SELECT ENAME FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING');

SELECT ENAME , SAL FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='CHICAGO');

SELECT * FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');

SELECT EMP.*,SAL*12 FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');

SELECT ENAME FROM EMP WHERE DEPTNO= (SELECT DEPTNO FROM DEPT WHERE DNAME='OPERATIONS');

-- NESTED SUBQUERY

SELECT MAX(SAL) FROM EMP WHERE  SAL<(SELECT MAX(SAL) FROM EMP);

SELECT MAX(SAL) FROM EMP WHERE  SAL<(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL)FROM EMP));

SELECT ENAME FROM EMP WHERE SAL=(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP));

SELECT DNAME FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE SAL=(SELECT MIN(SAL) FROM EMP WHERE SAL>(SELECT MIN(SAL) FROM EMP)));

SELECT MIN(HIREDATE) FROM EMP;

SELECT MIN(HIREDATE) FROM EMP WHERE HIREDATE> (SELECT MIN(HIREDATE) FROM EMP);

SELECT MAX(HIREDATE) FROM EMP;

SELECT LOC FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE HIREDATE=(SELECT MAX(HIREDATE)FROM EMP WHERE HIREDATE<(SELECT MAX(HIREDATE) FROM EMP)));

SELECT MIN(SAL) FROM EMP WHERE SAL>(SELECT MIN(SAL) FROM EMP);

SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL)FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP))));

SELECT EMPNO FROM EMP WHERE SAL=(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP) );

SELECT DNAME FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE SAL=(SELECT MAX(SAL)FROM EMP WHERE SAL<(SELECT MAX(SAL)FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL)FROM EMP)))));

SELECT * FROM EMP WHERE HIREDATE =(SELECT MIN(HIREDATE) FROM EMP WHERE HIREDATE>(SELECT MIN(HIREDATE) FROM EMP));

SELECT ENAME FROM EMP WHERE HIREDATE = (SELECT MAX(HIREDATE) FROM EMP WHERE HIREDATE<(SELECT MAX(HIREDATE) FROM EMP));

SELECT LOC FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE HIREDATE=(SELECT MIN(HIREDATE) FROM EMP));

SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP)));

-- EMPLOYEE MANAGER RELATION 

-- CASE1: TO FIND MANAGER

SELECT ENAME FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='ALLEN');

SELECT SAL FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='SMITH');

SELECT ENAME FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='JAMES'));

SELECT DNAME FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='SMITH'));

SELECT ENAME FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='SMITH');

SELECT ENAME FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='ADAMS'));

SELECT DNAME FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='JAMES'));

SELECT SAL FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME ='MILLER'));

SELECT LOC FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='SMITH')));

-- CASE2: TO FIND EMPLOYEE

SELECT ENAME FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='JAMES');

SELECT COUNT(*) FROM EMP WHERE MGR= (SELECT EMPNO FROM EMP WHERE ENAME='KING');

-- PSEDUOCOLUMNS: ROWNUM:

SELECT ROWNUM, EMP.* FROM EMP WHERE ROWNUM=1;

SELECT * FROM (SELECT ROWNUM AS SINO ,EMP.* FROM EMP) WHERE SINO=2;

SELECT * FROM (SELECT ROWNUM AS SINO, EMP.* FROM EMP) WHERE SINO<4;

SELECT * FROM (SELECT ROWNUM AS SINO, EMP.* FROM EMP) WHERE SINO<(SELECT COUNT(*)/2 FROM EMP);

SELECT * FROM (SELECT ROWNUM AS SINO, EMP.* FROM EMP) WHERE SINO>(SELECT COUNT(*)/2 FROM EMP);

SELECT * FROM (SELECT ROWNUM AS SINO, EMP.* FROM EMP) WHERE SINO>(SELECT COUNT(*)-5 FROM EMP);

-- FIND MIN, MAX USING PSEDUOCOLUMNS

SELECT SAL FROM (SELECT ROWNUM AS SINO, SAL FROM (SELECT DISTINCT(SAL) FROM EMP ORDER BY SAL DESC));

-- JOINS

-- INNER JOINS

SELECT ENAME, DNAME FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO;

SELECT ENAME, LOC, JOB FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND JOB='CLERK';

SELECT ENAME, SAL, HIREDATE, DNAME FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND SAL>2000 AND DNAME='ACCOUNTING';

SELECT ENAME, SAL, EMP.DEPTNO, LOC FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND JOB='MANAGER' AND LOC='DALLAS';

SELECT ENAME, HIREDATE, LOC FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND HIREDATE>='01-JAN-82' AND JOB='ANALYST' AND EMP.DEPTNO=10;

SELECT ENAME, LOC FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO;

SELECT DNAME, SAL FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND DNAME='ACCOUNTING';

SELECT DNAME, SAL*12 AS ANNUAL_SAL FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND SAL>2340;

SELECT ENAME, DNAME FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND DNAME LIKE '%A%';

SELECT ENAME, DNAME FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND JOB='SALESMAN';

SELECT DNAME, JOB FROM EMP, DEPT WHERE ENAME LIKE 'S%' AND DNAME LIKE '%S';

SELECT DNAME, MGR FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND MGR=7839;

SELECT ENAME, DNAME FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND COMM IS NOT NULL AND EMP.DEPTNO IN (10 ,30);

SELECT DNAME, EMPNO FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND EMPNO IN (7839,7902) AND LOC='NEW YORK';

-- SELF JOIN

SELECT * FROM EMP E1, EMP E2 WHERE E2.EMPNO=E1.MGR;

SELECT E1.ENAME, E1.JOB, E2.ENAME ,E2.JOB FROM EMP E1,EMP E2 WHERE E2.EMPNO=E1.MGR AND E1.JOB='CLERK' AND E2.JOB='ANALYST';

SELECT E1.ENAME, E1.HIREDATE, E1.SAL, E2.ENAME, E2.JOB, E2.SAL FROM EMP E1, EMP E2 WHERE E1.MGR=E2.EMPNO AND E1.HIREDATE<E2.HIREDATE AND E2.SAL>E1.SAL; 

SELECT E1.ENAME, E2.ENAME FROM EMP E1, EMP E2 WHERE E1.MGR=E2.EMPNO AND E1.JOB='CLERK';

SELECT E1.ENAME, E2.ENAME, E3.ENAME FROM EMP E1, EMP E2, EMP E3 WHERE E1.MGR=E2.EMPNO AND E2.MGR=E3.EMPNO;

SELECT E1.ENAME, E2.JOB FROM EMP E1, EMP E2 WHERE E1.MGR=E2.EMPNO AND E2.DEPTNO IN (10,20);

SELECT E1.ENAME, E2.SAL FROM EMP E1, EMP E2 WHERE E1.MGR=E2.EMPNO AND E1.SAL>2300 AND E2.SAL>2300;

SELECT E1.ENAME, E2.HIREDATE FROM EMP E1, EMP E2 WHERE E1.MGR=E2.EMPNO AND E1.HIREDATE<'01-JAN-82';

SELECT E1.ENAME, E2.COMM FROM EMP E1, EMP E2 WHERE E1.MGR=E2.EMPNO AND E1.JOB='SALESMAN' AND E2.DEPTNO =30;

SELECT E1.ENAME, E2.ENAME, E1.SAL, E2.SAL FROM EMP E1, EMP E2 WHERE E1.SAL>E2.SAL AND E1.MGR=E2.EMPNO;

SELECT E1.ENAME, E1.HIREDATE, E2.ENAME, E2.HIREDATE FROM EMP E1, EMP E2 WHERE E2.HIREDATE<E1.HIREDATE AND E1.MGR=E2.EMPNO;

SELECT E1.ENAME, E2.ENAME FROM EMP E1, EMP E2 WHERE E1.MGR=E2.EMPNO AND E1.JOB=E2.JOB;

SELECT E1.ENAME, E2.ENAME FROM EMP E1, EMP E2 WHERE E1.MGR=E2.EMPNO AND E2.JOB='MANAGER';

SELECT E1.ENAME, E2.ENAME, E1.SAL*12 AS EMP_ANNUAL_SAL, E2.SAL*12 AS MGR_ANNUAL_SAL FROM EMP E1, EMP E2 WHERE E1.MGR=E2.EMPNO AND E1.DEPTNO IN (10,20) AND E2.SAL>E1.SAL;

SELECT E1.ENAME, E2.JOB FROM EMP E1, EMP E2 WHERE E1.MGR=E2.EMPNO;

SELECT E1.ENAME, E2.SAL FROM EMP E1, EMP E2 WHERE E1.MGR=E2.EMPNO AND E2.SAL LIKE '%50';

-- COMBINATION OF INNER JOIN AND SELF JOIN

SELECT E1.ENAME, DNAME, E2.ENAME 
FROM EMP E1, EMP E2, DEPT 
WHERE E1.MGR=E2.EMPNO AND E1.DEPTNO=DEPT.DEPTNO;
                                        OR
SELECT E1.ENAME, D1.DNAME, E2.ENAME 
FROM EMP E1, EMP E2, DEPT D1 
WHERE E1.MGR=E2.EMPNO AND E1.DEPTNO=D1.DEPTNO;

SELECT E1.ENAME, E2.ENAME, D2.DNAME 
FROM EMP E1, EMP E2, DEPT D2 
WHERE E1.MGR=E2.EMPNO AND E2.DEPTNO=D2.DEPTNO;

SELECT E1.ENAME, E2.ENAME, D1.DNAME, D2.DNAME FROM EMP E1, EMP E2, DEPT D1, DEPT D2 WHERE E1.MGR=E2.EMPNO AND E1.DEPTNO= D1.DEPTNO AND E2.DEPTNO=D2.DEPTNO;

SELECT E1.ENAME, E2.ENAME, E3.ENAME, D1.DNAME, D2.DNAME, D3.DNAME FROM EMP E1, EMP E2, EMP E3, DEPT D1, DEPT D2, DEPT D3 WHERE E1.MGR=E2.EMPNO AND E2.MGR=E3.EMPNO AND E1.DEPTNO= D1.DEPTNO AND E2.DEPTNO=D2.DEPTNO AND E3.DEPTNO=D3.DEPTNO;

SELECT E1.ENAME, E2.ENAME , D1.LOC FROM EMP E1, EMP E2, DEPT D1 WHERE E1.JOB='CLERK' AND E1.MGR=E2.EMPNO AND E1.DEPTNO=D1.DEPTNO;

SELECT E1.ENAME, E2.SAL, D2.LOC FROM EMP E1, EMP E2, DEPT D2 WHERE E2.JOB='PRESIDENT' AND E1.MGR=E2.EMPNO AND E2.DEPTNO=D2.DEPTNO;

SELECT E1.ENAME, E1.SAL, E2.ENAME, E2.SAL , D1.DNAME FROM EMP E1, DEPT D1, EMP E2 WHERE E1.MGR=E2.EMPNO AND E1.DEPTNO=D1.DEPTNO AND E1.SAL>E2.SAL;

SELECT E1.ENAME, E1.SAL, E2.ENAME, D2.DNAME FROM EMP E1, EMP E2, DEPT D2 WHERE E1.MGR=E2.EMPNO AND E2.DEPTNO=D2.DEPTNO AND D2.LOC='NEW YORK' AND E2.SAL>3000;

SELECT E1.ENAME, D1.DNAME, E2.ENAME, D2.DNAME FROM EMP E1, EMP E2, DEPT D1, DEPT D2 WHERE E1.MGR=E2.EMPNO AND E1.DEPTNO= D1.DEPTNO AND E2.DEPTNO=D2.DEPTNO AND D1.LOC=D2.LOC;

SELECT E1.ENAME, E1.HIREDATE, E2.HIREDATE FROM EMP E1, EMP E2, DEPT D1 WHERE E2.HIREDATE<E1.HIREDATE AND E1.MGR=E2.EMPNO AND E1.DEPTNO=D1.DEPTNO AND D1.DNAME='ACCOUNTING' ;

SELECT E1.ENAME, D1.DNAME, E2.ENAME, D2.DNAME FROM EMP E1, EMP E2, DEPT D1, DEPT D2 WHERE E1.MGR=E2.EMPNO AND E1.DEPTNO=D1.DEPTNO AND E2.DEPTNO= D2. DEPTNO AND E2.HIREDATE<'01-JAN-82';

SELECT E1.ENAME, D1.DNAME, E2.ENAME, D2.LOC, E3.ENAME, D3.LOC FROM EMP E1, EMP E2, EMP E3, DEPT D1, DEPT D2, DEPT D3 WHERE E1.MGR=E2.EMPNO AND E2.MGR=E3.EMPNO AND E1.DEPTNO=D1.DEPTNO AND E2.DEPTNO=D2.DEPTNO AND E3.DEPTNO=D3.DEPTNO;

SELECT E1.ENAME, D1.DNAME, E2.SAL, D2.DNAME, E3.JOB, D3.DNAME FROM EMP E1, DEPT D1, EMP E2, DEPT D2, EMP E3, DEPT D3 WHERE E1.MGR=E2.EMPNO AND E2.MGR=E3.EMPNO AND E1.DEPTNO=D1.DEPTNO AND E2.DEPTNO=D2.DEPTNO AND E3.DEPTNO=D3.DEPTNO AND E1.DEPTNO=10 AND E2.JOB IN('PRESIDENT','MANAGER') AND E3.SAL>=E2.SAL;

-- CORELATED SUBQUERY

SELECT DNAME 
FROM DEPT 
WHERE DEPTNO IN ( 
    SELECT DEPTNO 
    FROM EMP 
    WHERE DEPT.DEPTNO= EMP.DEPTNO
    );


SELECT E1.SAL 
FROM EMP E1 
WHERE ( 
    SELECT COUNT(DISTINCT E2.SAL) 
    FROM EMP E2 
    WHERE E1.SAL<=E2.SAL
    ) 
IN 3;



SELECT E1.SAL 
FROM EMP E1 
WHERE ( 
    SELECT COUNT(DISTINCT E2.SAL) 
    FROM EMP E2 
    WHERE E1.SAL<=E2.SAL
    ) 
IN (1,2,3);



SELECT E1.SAL 
FROM EMP E1 
WHERE (
    SELECT COUNT(DISTINCT E2.SAL) 
    FROM EMP E2 
    WHERE E1.SAL>=E2.SAL) 
IN (1,2,3);


-- WINDOWS FUNCTION 

SELECT * 
FROM (
    SELECT ENAME,SAL,DEPTNO, ROW_NUMBER() 
    OVER (
        PARTITION BY DEPTNO 
        ORDER BY SAL DESC
        ) 
    AS EMPSAL 
    FROM EMP
    ) 
WHERE EMPSAL<=3;

SELECT * FROM ( SELECT ENAME,SAL,DEPTNO,DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC ) AS EMPSAL FROM EMP) WHERE EMPSAL<=3;

SELECT * FROM ( SELECT ENAME,SAL,DEPTNO,RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC ) AS EMPSAL FROM EMP) WHERE EMPSAL<=3;

SELECT * FROM (SELECT ENAME,SAL,DEPTNO, ROW_NUMBER() OVER (ORDER BY SAL DESC) AS EMPSAL FROM EMP) WHERE EMPSAL<=3;

SELECT * FROM ( SELECT ENAME,SAL,DEPTNO,DENSE_RANK() OVER(ORDER BY SAL DESC ) AS EMPSAL FROM EMP) WHERE EMPSAL<=3;

SELECT * FROM ( SELECT ENAME,SAL,DEPTNO,RANK() OVER(ORDER BY SAL DESC ) AS EMPSAL FROM EMP) WHERE EMPSAL<=3;
